ci

diff --git a/.github/workflows/build.yml b/.github/workflows/build.yml
--- a/.github/workflows/build.yml
+++ b/.github/workflows/build.yml
@@ -37,9 +37,14 @@ jobs:
           unset RUSTUP_UPDATE_ROOT
           unset CARGO_HTTP_MULTIPLEXING
           # 删除或重置全局配置
-          rm ${CARGO_HOME}/config.toml || true
-          rm -rf rm ${CARGO_HOME}/registry/* || true
+          rm -f ${CARGO_HOME}/config.toml || true
+          rm -rf ${CARGO_HOME}/registry/* || true
       - uses: actions/checkout@v4
+      - name: Print Cargo source info
+        run: |
+          echo "==== Print Cargo source info ===="
+          cargo search test -v || echo "cargo search failed"
+          echo "==== End Cargo source info ===="
       - name: Run tests
         run: |
           qemu-system-riscv64 --version
